#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6g

#Gradle
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
#org.gradle.caching=true

#wasm.multimodule=false
#
#kotlin.build.report.output=file
#kotlin.build.report.verbose=true

#org.gradle.debug=true
#kotlin.compiler.execution.strategy=in-process

org.gradle.caching=false